services:
  desktop:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: lxde-novnc
    ports:
      - "6080:6080"
      - "5900:5900"
    environment:
      - VNC_USER=docker
      - VNC_PASS=letmein
    restart: unless-stopped